// src/app/header/header.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-header',
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss'
})
export class HeaderComponent {
  isMenuOpen = false;

  handleMenuClick(): void {
    this.isMenuOpen = !this.isMenuOpen;
  }

  handleNavLinkClick(): void {
    this.isMenuOpen = false;
  }

  handleLogoClick(): void {
    window.location.href = './';
  }
}

<div class="Header-container">
  <div class="logo" (click)="handleLogoClick()">
    <img src="../../assets/logo.png" id="logo" alt="Logo" />
  </div>
  <div class="menu-icon" (click)="handleMenuClick()">
    <i [class]="isMenuOpen ? 'fas fa-times' : 'fas fa-bars'"></i>
  </div>
  <nav [class]="isMenuOpen ? 'navbar active' : 'navbar'">
    <ul id="navbar">
      <li>
        <a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{exact: true}" (click)="handleNavLinkClick()">Home</a>
      </li>
      <li>
        <a routerLink="/about" routerLinkActive="active" (click)="handleNavLinkClick()">About</a>
      </li>
      <li>
        <a routerLink="/portfolio" routerLinkActive="active" (click)="handleNavLinkClick()">Portfolio</a>
      </li>
      <li>
        <a routerLink="/contact" routerLinkActive="active" (click)="handleNavLinkClick()">Contact</a>
      </li>
    </ul>
  </nav>
</div>

// src/components/Header/Header.tsx
import React, { useState } from 'react';
import { NavLink } from 'react-router-dom';
import './Header.scss';
import logo from '../../assets/logo.png';

const Header: React.FC = () => {
  const [isMenuOpen, setIsMenuOpen] = useState<boolean>(false);

  const handleMenuClick = (): void => {
    setIsMenuOpen(!isMenuOpen);
  };

  const handleNavLinkClick = (): void => {
    setIsMenuOpen(false);
  };

  const handleLogoClick = (): void => {
    window.location.href = './';
  };

  return (
    <div className="Header-container">
      <div className="logo" onClick={handleLogoClick}>
        <img src={logo} id="logo" alt="Nice's Portfolio Logo" />
      </div>
      <div className="menu-icon" onClick={handleMenuClick}>
        <i className={isMenuOpen ? 'fas fa-times' : 'fas fa-bars'}></i>
      </div>
      <nav className={isMenuOpen ? 'navbar active' : 'navbar'}>
        <ul id="navbar">
          <li>
            <NavLink to="/" onClick={handleNavLinkClick}>
              Home
            </NavLink>
          </li>
          <li>
            <NavLink to="/about" onClick={handleNavLinkClick}>
              About
            </NavLink>
          </li>
          <li>
            <NavLink to="/portfolio" onClick={handleNavLinkClick}>
              Portfolio
            </NavLink>
          </li>
          <li>
            <NavLink to="/contact" onClick={handleNavLinkClick}>
              Contact
            </NavLink>
          </li>
        </ul>
      </nav>
    </div>
  );
};

Header.displayName = 'Header';

export default Header;
