// src/app/pages/portfolio/portfolio.component.ts
import { Component, OnInit } from '@angular/core';
import { NgFor, NgIf } from '@angular/common';
import projects, { Project } from '../../data/projects';

@Component({
  selector: 'app-portfolio',
  imports: [NgFor, NgIf],
  templateUrl: './portfolio.component.html',
  styleUrl: './portfolio.component.scss'
})
export class PortfolioComponent implements OnInit {
  projects: Project[] = projects;
  selectedProject: Project | null = null;
  isModalOpen = false;

  ngOnInit(): void {
    document.title = 'Portfolio | Niclas Sch&aelig;ffer Portfolio';
  }

  openModal(project: Project): void {
    this.selectedProject = project;
    this.isModalOpen = true;
  }

  closeModal(): void {
    this.isModalOpen = false;
    this.selectedProject = null;
  }

  openLivePreview(): void {
    if (this.selectedProject?.livepreviewurl) {
      window.open(this.selectedProject.livepreviewurl, '_blank');
    }
  }

  openGithub(): void {
    if (this.selectedProject?.githuburl) {
      window.open(this.selectedProject.githuburl, '_blank');
    }
  }
}

﻿<div class="Portfolio">
  <section class="heading">
    <div class="title">
      <h4>Portfolio</h4>
      <div class="underline"></div>
    </div>
  </section>

  <section class="subheading">
    <div class="subtitle">What Services You Will Get From Me</div>
    <div class="description">
      Here is a list over my last projects, so you can have a sneak peek and
      see. You can click on the projects and it will direct you to the
      project. Feel free to contact me for more information about the
      projects.
    </div>
    <div class="underline"></div>
  </section>

  <section class="projects-grid">
    <div class="project-box" *ngFor="let project of projects" (click)="openModal(project)">
      <img [src]="project.imgURL" [alt]="project.title" class="project-image" />
    </div>
  </section>

  <div class="modal-wrapper" *ngIf="isModalOpen && selectedProject" (click)="closeModal()" role="dialog" aria-modal="true">
    <div class="modal" (click)="$event.stopPropagation()">
      <div class="content">
        <span class="close" (click)="closeModal()" role="button" tabindex="0" aria-label="Close modal">
          &times;
        </span>
        <img class="image" [src]="selectedProject.imgURL" [alt]="selectedProject.title" />
        <h2 class="title">{{ selectedProject.title }}</h2>
        <p class="detail">{{ selectedProject.detail }}</p>
        
        <div class="accounts" *ngIf="selectedProject.accounts && selectedProject.accounts.length > 0">
          <p><strong>Demo Accounts:</strong></p>
          <ul>
            <li *ngFor="let account of selectedProject.accounts">{{ account }}</li>
          </ul>
        </div>
        
        <p class="techstack">
          <strong>TechStack used:</strong> {{ selectedProject.tech.join(', ') }}
        </p>
        
        <div class="btns">
          <button 
            class="livepreview" 
            [class.disabled]="!selectedProject.livepreviewurl"
            (click)="openLivePreview()"
            [disabled]="!selectedProject.livepreviewurl">
            Live Preview
          </button>
          <button class="Github" (click)="openGithub()">
            Github Repository
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

// src/components/Portfolio.jsx
import React, { useState } from 'react';
import './Portfolio.scss';
import projects from "../assets/projects";

function Portfolio() {
  const [selectedProject, setSelectedProject] = useState(null);
  document.title = 'Portfolio';

  const onProjectclick = (project) => {
    setSelectedProject(project);
  };

  const closeModal = () => {
    setSelectedProject(null);
  };

  const handleClicklive = () => {
    if (selectedProject?.livepreviewurl) {
      window.open(selectedProject.livepreviewurl);
    }
  };

  const handleClickGit = () => {
    window.open(selectedProject.githuburl);
  };

  const projectsContent = projects.map((project, index) => (
    <div key={project.id} className='project-box' onClick={() => onProjectclick(project)}>
      <img src={project.imgURL} alt={project.title} className='project-image' />
    </div>
  ));

  return (
    <div className="Portfolio">
      <section className='heading'>
        <div className='title'>
          <h4>Portfolio</h4>
          <div className='underline'></div>
        </div>
      </section>

      <section className='subheading'>
        <div className='subtitle'>What Services You Will Get From Me</div>
        <div className='description'>
          Here is a list over my last projects, so you can have a sneak peek and see. You can click on the projects
          and it will direct you to the project. Feel free to contact me for more information about the projects.
        </div>
        <div className='underline'></div>
      </section>

      <section className='projects-grid'>{projectsContent}</section>

      {selectedProject && (
        <div className="modal-wrapper" onClick={closeModal}>
          <div className="modal">
            <div className="content">
              <span className="close" onClick={closeModal}>&times;</span>
              <img className='image' src={selectedProject.imgURL} alt='project'></img>
              <h2 className='title'>{selectedProject.title}</h2>
              <p className='detail'>{selectedProject.detail}</p>
              {selectedProject.accounts && (
                <p>
                  {selectedProject.accounts.map((account, index) => (
                    <React.Fragment key={index}>
                      {account}
                      {index < selectedProject.accounts.length - 1 && <br />}
                    </React.Fragment>
                  ))}
                </p>
              )}
              <p className='techstack'><b>TechStack used:</b> {selectedProject.tech.join(", ")}</p>
              <div className="btns">
                <button
                  className={`livepreview ${!selectedProject.livepreviewurl ? "disabled" : ""}`}
                  onClick={handleClicklive}
                  disabled={!selectedProject.livepreviewurl}
                >
                  Live Preview
                </button>
                <button className='Github' onClick={handleClickGit}>Github Repository</button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export default Portfolio;
